name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++

    steps:
      - uses: actions/checkout@v5

      - name: Cache CMake deps
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-
            ${{ runner.os }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          ccache: true

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest
